name: Run curieconf Python tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache curieconf python dependencies
        uses: actions/cache@v2
        id: cache-curieconf-python-dependencies
        env:
          cache-name: cache-curieconf-python-dependencies

        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('curiefense/curieconf/**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('curiefense/curieconf/**/setup.py') }}

      - name: Install dependencies
        run: |
          pip install pytest wheel pytest-custom_exit_code
          cd "$GITHUB_WORKSPACE/curiefense/curieconf/utils"
          pip3 install -e .
          cd "$GITHUB_WORKSPACE/curiefense/curieconf/client"
          pip3 install -e .
          cd "$GITHUB_WORKSPACE/curiefense/curieconf/server"
          pip3 install -e .

      - name: Test with pytest
        run: |
          cd "$GITHUB_WORKSPACE/curiefense/curieconf/test"
          pytest "--junitxml=$GITHUB_WORKSPACE/junit.xml" --suppress-tests-failed-exit-code

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@70b5dd187f73f17a3b4ac0191e22bb9eec9bbb25
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Unit Test Results
          comment_title: Unit Test Statistics
          hide_comments: all but latest
          comment_on_pr: true
          files: junit.xml
          report_individual_runs: true
          deduplicate_classes_by_file_name: false
